version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_GPASSWORD: p@ssw0rd42
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  embulk:
    build: ./embulk

  digdag:
    build: ./digdag
    ports:
      - '65432:65432'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - ./digdag/log:/digdag/log
    depends_on:
      - postgres
